spring.application.name=clienti-service

spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=LouPostgres2020
spring.jpa.properties.hibernate.default_schema=exim
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true

springdoc.swagger-ui.path=/swagger-ui.html

server.port=8080
